# Kitty config

# Theme: Catppuccin Mocha
color_scheme Catppuccin Mocha

# Fonts & appearance
include ~/.config/kitty/themes/mocha.conf
font_family      Mona Sans Mono ExtraLight
font_size        16
cursor_style     block
copy_on_select   clipboard

# Behavior
shell            /opt/homebrew/bin/zsh
enable_audio_bell     no

# Keyboard - pass alt+left/right through to tmux for pane resizing
map alt+left   send_text all \x1b[1;3D
map alt+right  send_text all \x1b[1;3C
