#!/usr/bin/env bash

svgs=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.svg')
if [ -n "$svgs" ]; then
  echo $svgs | svgo --pretty && git add $svgs
fi

git secrets --pre_commit_hook -- "$@"
