#!/bin/sh

images=$(git diff --exit-code --cached --name-only --diff-filter=ACM -- '*.png' '*.jpg')
if [ -n "$images" ]; then
  echo $images | imageoptim && git add $images
fi

count=`grep -iR 'console\.log' **/javascripts/* | wc -l | awk '{print $1}'`
if [[ "$count" -ge 2 ]]; then
  echo "    remove any config.log() statements in javascript sources"
  exit 1
fi
